# Generated by Django 2.1 on 2018-08-29 14:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_lodd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodd',
            name='batch',
        ),
        migrations.AddField(
            model_name='sjanse',
            name='tall',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.DeleteModel(
            name='Lodd',
        ),
    ]
