# Generated by Django 2.1 on 2018-09-06 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_auto_20180906_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
