# Generated by Django 2.1 on 2018-09-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0006_auto_20180906_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='all_tickets',
            new_name='my_tickets',
        ),
    ]
