# Generated by Django 2.0.5 on 2018-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_auto_20180906_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
